# Generated by Django 5.2.3 on 2026-08-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('ai_advisor', 'Context-Aware AI Advisor (conversational)'), ('strategy_planner', 'AI Strategy Planner (analytical)'), ('profile_improvement', 'Profile Improvement Advisor (analytical)')], max_length=30)),
                ('user_question', models.TextField(blank=True, help_text="The student's free-form question (AI Advisor only, FR-10). Blank for Strategy Planner / Profile Improvement Advisor, which are triggered by a fixed request, not an open question.")),
                ('facts_bundle_snapshot', models.JSONField(default=dict, help_text='Exact Facts Bundle sent to Gemini for this interaction (never raw DB access — see apps.ai_advisor app docstring).')),
                ('ai_response_text', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('answered', 'Answered from Facts Bundle'), ('insufficient_info', 'Declined — Insufficient Information'), ('fallback_no_ai', 'Gemini Unavailable — Deterministic Fallback Used'), ('error', 'Gemini Request Failed (Error)')], help_text='Whether Gemini answered from the bundle, declined per FR-19, or the deterministic fallback was used because Gemini was unavailable (FR-22).', max_length=30)),
                ('gemini_model_name', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'interaction_type'], name='ai_advisor__student_72ea92_idx'), models.Index(fields=['outcome'], name='ai_advisor__outcome_f742c4_idx')],
            },
        ),
    ]
