# Generated by Django 5.2.3 on 2026-08-30 15:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('missing_info', 'Missing Information')], max_length=20)),
                ('explanation', models.CharField(blank=True, help_text='Plain-language reason, e.g. "CGPA is 3.2; required is 3.5" (FR-07). Blank when status is ELIGIBLE.', max_length=500)),
                ('quantified_gap', models.CharField(blank=True, help_text='Exact shortfall where numeric, e.g. "+0.3 CGPA" (FR-07). Feeds FR-08 (readiness) and FR-23 (Profile Improvement Advisor).', max_length=100)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_results', to='scholarships.scholarshipcriterion')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_results', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_results', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'scholarship'], name='recommendat_student_919dae_idx'), models.Index(fields=['status'], name='recommendat_status_86db44_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'scholarship', 'criterion'), name='unique_eligibility_per_student_scholarship_criterion')],
            },
        ),
        migrations.CreateModel(
            name='ReadinessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_items_count', models.PositiveIntegerField()),
                ('completed_items_count', models.PositiveIntegerField()),
                ('readiness_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('missing_items', models.JSONField(default=list, help_text='e.g. ["Recommendation Letter", "Income Certificate"].')),
                ('action_plan', models.JSONField(default=list, help_text='Ordered list of recommended next actions (FR-08), e.g. ["Request the recommendation letter first (longer lead time)."].')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_results', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_results', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'readiness_percent'], name='recommendat_student_2b7ed0_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'scholarship'), name='unique_readiness_per_student_scholarship')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_score_percent', models.DecimalField(decimal_places=2, help_text="Weighted Match Score using this scholarship's own criteria weights only (FR-06) — never comparable across scholarships on formula alone (SRS §4.1).", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('breakdown', models.JSONField(default=dict, help_text='Per-criterion contribution, e.g. {"cgpa": 100, "department": 100, "income": 80, "skills": 60}.')),
                ('weak_criteria', models.JSONField(default=list, help_text="Criteria explicitly flagged as weak/unmatched (FR-06: 'Weak or unmatched criteria shall be flagged explicitly').")),
                ('computed_at', models.DateTimeField(auto_now=True, help_text='When this cached result was last (re)computed.')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-match_score_percent'],
                'indexes': [models.Index(fields=['student', 'match_score_percent'], name='recommendat_student_e78436_idx'), models.Index(fields=['scholarship'], name='recommendat_scholar_a82ae3_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'scholarship'), name='unique_recommendation_per_student_scholarship')],
            },
        ),
    ]
