# Generated by Django 5.2.3 on 2026-08-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationresult',
            options={'ordering': ['-match_score_percent', '-id']},
        ),
    ]
