# Generated by Django 5.2.3 on 2026-08-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='applicationstatushistory',
            options={'ordering': ['created_at', 'id'], 'verbose_name_plural': 'Application status histories'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
