# Generated by Django 5.2.3 on 2026-08-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('account_registered', 'Account Registered'), ('profile_updated', 'Profile Updated'), ('provider_approved', 'Provider Approved'), ('provider_rejected', 'Provider Rejected'), ('scholarship_created', 'Scholarship Created'), ('scholarship_updated', 'Scholarship Updated'), ('scholarship_published', 'Scholarship Published'), ('scholarship_unpublished', 'Scholarship Unpublished'), ('scholarship_closed', 'Scholarship Deactivated/Closed'), ('scholarship_moderated', 'Scholarship Moderated by Administrator'), ('criterion_created', 'Eligibility Criterion Created'), ('criterion_updated', 'Eligibility Criterion Updated'), ('criterion_deleted', 'Eligibility Criterion Deleted'), ('weight_changed', 'Criterion Weight Changed'), ('application_status_changed', 'Application Status Changed'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('other', 'Other')], max_length=40)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action. Null for system-initiated events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='audit_audit_event_t_4496ba_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx'), models.Index(fields=['related_content_type', 'related_object_id'], name='audit_audit_related_1bf879_idx')],
            },
        ),
    ]
