# Generated by Django 5.2.3 on 2026-08-30 15:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Award amount in BDT.', max_digits=12)),
                ('deadline', models.DateTimeField()),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='Document names a student must submit, e.g. ["Recommendation Letter", "Income Certificate"]. Descriptive only — an eligibility rule tied to a document goes on ScholarshipCriterion (criterion_type=DOCUMENTS) instead.')),
                ('application_instructions', models.TextField(blank=True, help_text='Free-text guidance for applicants, e.g. how/where to submit.')),
                ('is_active', models.BooleanField(default=True, help_text='False if withdrawn by the provider or deactivated by an administrator (moderation). Independent of is_published and of deadline-based expiry — see is_expired.')),
                ('is_published', models.BooleanField(default=False, help_text='Only True once criteria weights sum to 100% (FR-04). Unpublished scholarships never enter recommendation scoring (FR-06) or student-facing search (FR-05).')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion_type', models.CharField(choices=[('cgpa', 'CGPA'), ('department', 'Department'), ('academic_level', 'Academic Level'), ('income', 'Family Income'), ('location', 'Location'), ('skills', 'Skills'), ('documents', 'Required Documents'), ('other', 'Other')], max_length=20)),
                ('comparison', models.CharField(choices=[('gte', 'Greater than or equal to'), ('lte', 'Less than or equal to'), ('equals', 'Equals'), ('contains', 'Contains / Includes')], max_length=10)),
                ('required_value', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=True, help_text="If False, failing this criterion contributes to 'near-eligible' classification (FR-20) rather than hard ineligibility. Interpreted by the eligibility service.")),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipCriterionWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_percent', models.DecimalField(decimal_places=2, help_text="This criterion's share of the scholarship's Match Score, e.g. 40.00 for 40%. All weights for one scholarship must sum to exactly 100% before scoring/publishing (FR-04, FR-06).", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('criterion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='scholarships.scholarshipcriterion')),
                ('set_by', models.ForeignKey(blank=True, help_text='Provider user who last set this weight (for audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['is_published'], name='scholarship_is_publ_ecfc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['is_active'], name='scholarship_is_acti_62e7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['deadline'], name='scholarship_deadlin_f24616_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipcriterion',
            index=models.Index(fields=['criterion_type'], name='scholarship_criteri_602e83_idx'),
        ),
        migrations.AddConstraint(
            model_name='scholarshipcriterion',
            constraint=models.UniqueConstraint(condition=models.Q(('criterion_type__in', ['cgpa', 'department', 'academic_level', 'income', 'location'])), fields=('scholarship', 'criterion_type'), name='unique_builtin_criterion_type_per_scholarship'),
        ),
        migrations.AddIndex(
            model_name='scholarshipcriterionweight',
            index=models.Index(fields=['weight_percent'], name='scholarship_weight__73c121_idx'),
        ),
    ]
